name = "MeshGrid"
uuid = "ebf956a0-ef5e-43be-9fb1-27952996e635"
authors = ["Jake W. Liu"]
version = "1.0.2"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
